### ISSUE TITLE
[regression] 'Manager' object has no attribute 'query'

### ISSUE THREAD

**Issue by open-dynaMIX** [projectcaluma/caluma#598]
#569 introduced a regression that is triggered in one of our projects.

Here is one example:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/promise/promise.py", line 487, in _resolve_from_executor
    executor(resolve, reject)
  File "/usr/local/lib/python3.6/site-packages/promise/promise.py", line 754, in executor
    return resolve(f(*args, **kwargs))
  File "/usr/local/lib/python3.6/site-packages/graphql/execution/middleware.py", line 75, in make_it_promise
    return next(*args, **kwargs)
  File "/app/caluma/core/filters.py", line 501, in connection_resolver
    **args,
  File "/usr/local/lib/python3.6/site-packages/graphene_django/fields.py", line 158, in connection_resolver
    queryset = cls.resolve_queryset(connection, default_manager, info, args)
  File "/usr/local/lib/python3.6/site-packages/graphene_django/fields.py", line 88, in resolve_queryset
    return connection._meta.node.get_queryset(queryset, info)
  File "/app/caluma/form/schema.py", line 152, in get_queryset
    queryset = super().get_queryset(queryset, info)
  File "/app/caluma/core/types.py", line 31, in get_queryset
    queryset = visibility_class().filter_queryset(cls, queryset, info)
  File "/app/caluma/core/visibilities.py", line 85, in filter_queryset
    result_queryset = result_queryset.union(class_result)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 946, in union
    return self._combinator_query('union', *other_qs, all=all)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 936, in _combinator_query
    clone.query.combined_queries = (self.query,) + tuple(qs.query for qs in other_qs)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 936, in <genexpr>
    clone.query.combined_queries = (self.query,) + tuple(qs.query for qs in other_qs)
graphql.error.located_error.GraphQLLocatedError: 'Manager' object has no attribute 'query'

[22/Jul/2019 12:15:02] "POST /graphql/ HTTP/1.0" 200 369
```

That's the query:

```
"query GetOptionsForFilter($slug: String!) {
  allQuestions(slug: $slug) {
    edges {
      node {
        id
        slug
        ... on ChoiceQuestion {
          options {
            edges {
              node {
                id
                slug
                label
                __typename
              }
              __typename
            }
            __typename
          }
          __typename
        }
        ... on MultipleChoiceQuestion {
          options {
            edges {
              node {
                id
                slug
                label
                __typename
              }
              __typename
            }
            __typename
          }
          __typename
        }
        __typename
      }
      __typename
    }
    __typename
  }
}
"
variables: {slug: "projektleiter"}
```

**Comment by sliverc** [comment]
I see the error and also why, not sure just yet how to reproduce it yet but most likely an error in combination with the union visibility class. Working on it.
